spring:
  config:
    activate:
      on-profile:
      - dev
accounts:
  message: "This contact is related to dev team config-server"
  contactDetails:
    name: sai.devireddy  
    email: 5d44fb6c72edf740fe0f45b4f3835a3a59a9126ba0bc6448c3e63e6e3fa41ccb2dfeea7db0b3d3c0361e0dd2bfb9aa6b
  contactNumber:
  - 7207413645
  - 8765678777
build:
  version: 1.3
