spring:
  config:
    activate:
      on-profile:
      - prod
accounts:
  message: "This contact is related to production team config-server"
  contactDetails:
    name: naveen.devireddy  
    email: naveen-prod-test@gmail.com
  contactNumber:
  - 7207413645
  - 8765678777
build:
  version: 1.4
