spring:
  config:
    activate:
      on-profile:
      - qa
accounts:
  message: "This Cards Ms, contact to QA team"
  contactDetails:
    name: sai.devireddy  
    email: sai-qa@gmail.com
  contactNumber:
  - 7207413645
  - 8765678777
build:
  version: "cards-qa-1.3"
