spring:
  config:
    activate:
      on-profile:
      - prod
accounts:
  message: "This Cards Ms, contact to Prod team"
  contactDetails:
    name: sai.devireddy  
    email: sai@gmail.com
  contactNumber:
  - 7207413645
  - 8765678777
build:
  version: "cards-prod-1.3"